### ISSUE TITLE
Update axios dependency

### ISSUE THREAD

**Issue by ooloth** [diegolamanno/gatsby-source-greenhouse#11]
GitHub has identified the following security vulnerability related to `axios`:

> Axios up to and including 0.18.0 allows attackers to cause a denial of service (application crash) by continuing to accepting content after maxContentLength is exceeded.

GitHub recommends the following remediation:

> Upgrade axios to version 0.18.1 or later.

**Comment by diegolamanno** [comment]
#15 fixed that issue
